name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build with code coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle Wrapper
        run: ./gradlew build -DGOOGLE_SHEETS_CRED=${{ secrets.GOOGLE_SHEETS_CRED }}

      - name: Report code coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
